### ISSUE TITLE
Aren't you effectively 'looking into test data' due to negative sampling strategy?

### ISSUE THREAD

**Issue by apoorvumang** [otiliastr/coper#7]
Hi

From Appendix A, it seems to me that if (s, r, o) exists in test, then o is never chosen as a negative sample for any train triple (s,r,o'). This means that during training you have already seen into test data.

Am I missing something, or is this what is happening?

**Comment by gstoica27** [comment]
Hi, 

I'm not sure I understand where you see that we're test data in our negative sampling scheme. Could you please point me to the specific sentence(s)? 

To be clear though, we are not using any auxiliary (including test-validation) data in our negative sampling scheme; we only use the supervision given by the training set. 

The core idea behind the negative sampling step is that rather than declaring all non-positively labeled object entities as negative examples, we instead randomly sub-sample a set of them during each batch step. This way, we reduce the effect of erroneously assigning a "negative label" to an entity that is in fact positive (of course unknown to the model) in validation/test. However, this also means that we do not have any guarantee that actual positive "test" object entities are not sampled as negative entities during train -- in fact it is very likely that it happens throughout training. 

Does this make sense?

**Comment by apoorvumang** [comment]
![image](https://user-images.githubusercontent.com/1957903/137604323-9c387a9f-dbdd-42d8-9a45-3744321ca21e.png)

This made me believe that test entities were being filtered out during negative sampling.

Thanks for the clarification!
